use Adventure
select * from dbo.DimCurrency
select * from dbo.DimAccount
select * from dbo.FactFinance
select * from dbo.DimCustomer
select * from dbo.DimDate
select * from dbo.DimDepartmentGroup
select * from dbo.DimEmployee
select * from dbo.DimSalesTerritory
select * from dbo.DimGeography
select * from dbo.DimOrganization
select * from dbo.DimProduct
select * from dbo.DimProductCategory
select * from dbo.DimProductSubcategory
select * from dbo.DimPromotion
select * from dbo.DimReseller
select * from dbo.DimSalesReason
select * from dbo.FactInternetSalesReason
select * from dbo.FactInternetSales
select * from dbo.DimScenario
select * from dbo.FactCallCenter
select * from dbo.FactFinance
select * from dbo.FactProductInventory
select * from dbo.FactSalesQuota
select * from dbo.FactSurveyResponse
select * from dbo.NewFactCurrencyRate
select * from dbo.ProspectiveBuyer
